import { defineConfig } from "orval";

const config = defineConfig({
  api: {
    input: "http://localhost:3000/openapi.json",
    output: {
      target: "./src/__generated__/api.ts",
      client: "react-query",
      httpClient: "fetch",
      mode: "tags-split",
      clean: true,
      mock: true,
      prettier: true,
      override: {
        mutator: {
          path: "./src/lib/custom-fetch.ts",
          name: "customFetch",
        },
        transformer: (verb) => {
          if (verb.verb === "get") {
            return {
              ...verb,
              operationName: `${verb.operationId}Query`,
            };
          }
          if (
            verb.verb === "post" ||
            verb.verb === "put" ||
            verb.verb === "patch" ||
            verb.verb === "delete"
          ) {
            return {
              ...verb,
              operationName: `${verb.operationId}Mutation`,
            };
          }

          return verb;
        },
        header: (info) => [
          `Generated by orval 🍺`,
          `Do not edit manually.`,
          info.title,
          ...(info.description ? [info.description] : []),
          `OpenAPI spec version: ${info.version}`,
          "eslint-disable",
        ],
      },
    },
  },
});

export default config;
