name: Bug Report
description: バグや問題を報告するためのテンプレート
title: "[Bug] "
labels: ["bug", "needs triage"]
assignees: ["yuichiyasui"]
body:
  - type: markdown
    attributes:
      value: |
        バグレポートをありがとうございます。問題を迅速に解決するため、以下の情報をご記入ください。

  - type: input
    id: environment
    attributes:
      label: 環境情報
      description: Node.js バージョン、OS、ブラウザなど
      placeholder: "例: Node.js 20.x, macOS 14.x, Chrome 120.x"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期待される動作
      description: 何が起こることを期待していましたか？
      placeholder: "期待される動作を詳しく説明してください"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 実際の動作
      description: 実際に何が起こりましたか？
      placeholder: "実際に発生した問題を詳しく説明してください"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      description: 問題を再現するための手順を教えてください
      placeholder: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: ログ・エラーメッセージ
      description: 関連するログやエラーメッセージがあれば貼り付けてください
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 追加情報
      description: その他、問題解決に役立つ情報があれば記載してください
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 確認事項
      description: 以下の項目を確認してください
      options:
        - label: 類似の問題が既に報告されていないか検索しました
          required: true
        - label: 最新バージョンで問題が発生することを確認しました
          required: true
